export const icons = {
  aneySalesLogo: require('./aneySaleLogo.svg'),
  visitsTab: require('./visitsTab.svg'),
  visitsTabSelected: require('./visitsTabSelected.svg'),
  homeTab: require('./homeTab.svg'),
  homeTabSelected: require('./homeTabSelected.svg'),
  leadsTab: require('./leadsTab.svg'),
  leadsTabSelected: require('./leadsTabSelected.svg'),
  moreTab: require('./moreTab.svg'),
  moreTabsSelected: require('./moreTabsSelected.svg'),
  aneyLogoHome: require('./aneyLogoHome.svg'),
  searchField: require('./searchField.svg'),
  errorInfo: require('./errorInfo.svg'),
  search: require('./search.svg'),
  moreVertical: require('./moreVertical.svg'),
  backIcon: require('./backIcon.svg'),
  arrowDown: require('./arrowDown.svg'),
  addLead: require('./addLeads.svg'),
  plushWhite: require('./plushWhite.svg'),
  signOut: require('./SignOut.svg'),
  next: require('./next.svg'),
  checkMark: require('./CheckMark.svg'),
  calender: require('./calender.svg'),
  location: require('./location.svg'),
  closeIcon: require('./closeIcon.svg'),
  shareLink: require('./shareLink.svg'),
  marker: require('./marker.svg'),
  mapBack2: require('./mapBack2.svg'),
  screenBgLogo: require('./screenBgLogo.svg'),
  directionIcon: require('./directionIcon.svg'),
  phoneIcon: require('./phoneIcon.svg'),
  whastsAppIcon: require('./whastsAppIcon.svg'),
  eyeOn: require('./eye.svg'),
  eyeOff: require('./eyeOff.svg'),
  checkMarkSquare: require('./checkMarkSquare.svg'),
  arrowDownWhite: require('./arrowDownWhite.svg'),
  truckGreenIcon: require('./truckGreenIcon.svg'),
  truckIcon: require('./truckIcon.svg'),
};
  
  export type IconProps = keyof typeof icons | string;
  